# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: alexaWine # NOTE: update this with your service name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
# frameworkVersion: "=X.X.X"

provider:
  name: aws
  runtime: nodejs18.x
  memorySize: 512
  region: us-east-1
  stage: dev
  environment:
    WINE_API_KEY: ${env:WINE_API_KEY}
    WINE_API_BASE_URL: ${env:WINE_API_BASE_URL, 'https://services.wine.com/api/beta2/service.svc/JSON'}
    ALEXA_SKILL_ID: ${env:ALEXA_SKILL_ID, 'amzn1.ask.skill.db86c0db-cfb9-426f-99c5-dfc8406bd56f'}
    LOG_LEVEL: ${env:LOG_LEVEL, 'info'}

# you can overwrite defaults here
#  stage: dev
#  region: us-east-1

# you can add statements to the Lambda function's IAM Role here
#  iamRoleStatements:
#    - Effect: "Allow"
#      Action:
#        - "s3:ListBucket"
#      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
#    - Effect: "Allow"
#      Action:
#        - "s3:PutObject"
#      Resource:
#        Fn::Join:
#          - ""
#          - - "arn:aws:s3:::"
#            - "Ref" : "ServerlessDeploymentBucket"

# you can add packaging information here
package:
  exclude:
    - speechAssets/**
    - tests/**
    - test-api.js
    - README.md
    - .git/**
    - .ask/**
    - "*.csv"
  include:
    - wineDatabase.json
#  artifact: my-service-code.zip

functions:
  alexaWine:
    handler: index.handler
    description: "Wine Information Application (serverless deployment)"
    timeout: 3
